import { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { ShieldAlert, ChevronLeft, Map, Wind, TrendingUp, Zap, ArrowRight } from 'lucide-react';

export default function ScoreScreen() {
  const navigate = useNavigate();
  const location = useLocation();
  const data = location.state || {};
  
  const score = data.score || 84; 
  const premium = data.premium || 49; 
  const payout = data.payout || 250; 

  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleContinue = async () => {
    setIsSubmitting(true);
    
    try {
      const payload = {
        name: data.name || '',
        phone: data.phone || '',
        city: data.city || '',
        platform: data.platform || '',
        avg_earnings: Number(data.avg_earnings || 0),
        zone: data.zone || '',
        plan: data.plan || 'Basic'
      };

      await fetch('https://vsunihgsrnricqhofhsa.supabase.co/functions/v1/register-worker', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'apikey': 'YOUR_SUPABASE_ANON_KEY' // Replace with actual anon key
        },
        body: JSON.stringify(payload)
      });
    } catch (e) {
      console.log('Final registration api call simulated.');
    }

    setTimeout(() => {
      navigate('/dashboard', { state: data });
    }, 600);
  };

  return (
    <div className="container min-h-screen pt-12 pb-20 max-w-5xl mx-auto animate-fade-in relative">
      <button 
        onClick={() => navigate(-1)}
        className="text-text-secondary hover:text-white flex items-center gap-2 mb-8 transition-colors"
      >
        <ChevronLeft size={20} /> Back
      </button>

      {/* Decorative gradient */}
      <div className="absolute top-20 right-0 w-[500px] h-[500px] bg-accent-base/10 rounded-full blur-[120px] pointer-events-none z-0"></div>

      <div className="text-center mb-16 relative z-10">
        <div className="inline-flex items-center justify-center p-4 bg-accent-base/10 rounded-2xl mb-6 border border-accent-base/20 shadow-[0_0_30px_rgba(99,102,241,0.2)]">
           <Zap className="text-accent-base" size={32} />
        </div>
        <h1 className="text-4xl md:text-5xl font-display font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-b from-white to-white/70">
          AI Risk Assessment Score
        </h1>
        <p className="text-text-secondary text-lg max-w-2xl mx-auto">
          Your personalized trust profile generated by real-time geospatial data, historical weather patterns, and gig delivery metrics.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 relative z-10">
        
        {/* Main Score UI */}
        <div className="lg:col-span-5 flex flex-col justify-center items-center p-8 sm:p-10 glass-panel border-t-4 border-t-accent-base shadow-2xl relative overflow-hidden group">
          <div className="absolute inset-0 bg-gradient-to-b from-accent-base/5 to-transparent"></div>
          
          <h2 className="text-2xl font-bold text-white mb-2 relative z-10">Confidence Score</h2>
          <p className="text-text-secondary text-sm mb-12 text-center relative z-10">Calculated continuously via predictive modeling.</p>
          
          {/* Animated SVG Ring */}
          <div className="relative w-56 h-56 rounded-full border-[14px] border-white/5 flex items-center justify-center shadow-[0_0_60px_rgba(99,102,241,0.15)] bg-black/20 z-10">
            <svg className="absolute inset-0 w-full h-full -rotate-90">
              <circle 
                cx="112" cy="112" r="98" 
                className="stroke-accent-base drop-shadow-[0_0_10px_rgba(99,102,241,0.5)]" 
                strokeWidth="14" fill="none" 
                strokeDasharray="615" strokeDashoffset={615 - (615 * score) / 100}
                strokeLinecap="round" 
                style={{ transition: 'stroke-dashoffset 1.5s cubic-bezier(0.4, 0, 0.2, 1)' }}
              />
            </svg>
            <div className="text-center mt-2">
              <span className="text-6xl font-display font-extrabold text-white drop-shadow-md tracking-tighter">
                {score}
              </span>
              <span className="block text-accent-hover font-bold text-sm mt-1 uppercase tracking-widest bg-accent-base/20 px-3 py-1 rounded-full border border-accent-base/30">
                Excellent
              </span>
            </div>
          </div>
          
          <div className="w-full mt-12 bg-black/40 rounded-xl p-5 border border-white/10 flex justify-between items-center relative z-10 shadow-inner">
            <span className="text-text-secondary font-medium">Dynamic Premium Rate</span>
            <span className="font-extrabold text-white text-xl text-accent-base">₹{premium}<span className="text-sm font-medium text-text-secondary">/wk</span></span>
          </div>

          {/* Raw API Response Details */}
          <div className="w-full mt-4 bg-black/60 rounded-xl p-6 border border-white/10 font-mono text-[15px] space-y-3 relative z-10 shadow-inner">
            <p className="text-white">Score: {score} / 100</p>
            <p className="text-white">Premium: ₹{premium}</p>
            <p className="text-success-base">Payout: ₹{payout}</p>
          </div>

          <button 
            onClick={handleContinue}
            disabled={isSubmitting}
            className={`w-full mt-6 py-4 ${isSubmitting ? 'bg-accent-base/50 cursor-wait' : 'bg-accent-base hover:bg-accent-hover'} text-white rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-[0_0_20px_rgba(99,102,241,0.3)] relative z-10 hover:-translate-y-1`}
          >
            {isSubmitting ? 'Confirming...' : <>Continue to Dashboard <ArrowRight size={20} /></>}
          </button>
        </div>

        {/* Breakdown Factors */}
        <div className="lg:col-span-7 flex flex-col gap-4 justify-center">
           
           <div className="glass-panel p-6 flex items-center gap-5 hover:-translate-y-1 transition-all duration-300 border border-white/5 hover:border-blue-500/30 hover:bg-white-[0.03] group">
             <div className="p-4 bg-blue-500/10 rounded-2xl border border-blue-500/20 group-hover:bg-blue-500/20 transition-colors">
               <Wind className="text-blue-400" size={26} />
             </div>
             <div className="flex-1">
               <div className="flex justify-between items-center mb-1">
                  <h3 className="font-bold text-white text-lg">Hyper-Local Weather</h3>
                  <span className="text-blue-400 font-bold text-sm bg-blue-500/10 px-3 py-1 rounded-full">Low Risk</span>
               </div>
               <p className="text-sm text-text-secondary leading-relaxed mt-1">Algorithmic monsoon projections indicate only a 15% disruption probability in your primary delivery polygon.</p>
             </div>
           </div>

           <div className="glass-panel p-6 flex items-center gap-5 hover:-translate-y-1 transition-all duration-300 border border-white/5 hover:border-warning-base/30 hover:bg-white-[0.03] group">
             <div className="p-4 bg-warning-base/10 rounded-2xl border border-warning-base/20 group-hover:bg-warning-base/20 transition-colors">
               <Map className="text-warning-base" size={26} />
             </div>
             <div className="flex-1">
               <div className="flex justify-between items-center mb-1">
                  <h3 className="font-bold text-white text-lg">Geospatial Routing</h3>
                  <span className="text-warning-base font-bold text-sm bg-warning-base/10 px-3 py-1 rounded-full">Medium Risk</span>
               </div>
               <p className="text-sm text-text-secondary leading-relaxed mt-1">High congestion sectors combined with historical waterlogging density detected along regular routes.</p>
             </div>
           </div>

           <div className="glass-panel p-6 flex items-center gap-5 hover:-translate-y-1 transition-all duration-300 border border-white/5 hover:border-success-base/30 hover:bg-white-[0.03] group">
             <div className="p-4 bg-success-base/10 rounded-2xl border border-success-base/20 group-hover:bg-success-base/20 transition-colors">
               <TrendingUp className="text-success-base" size={26} />
             </div>
             <div className="flex-1">
               <div className="flex justify-between items-center mb-1">
                  <h3 className="font-bold text-white text-lg">Income Stability Pattern</h3>
                  <span className="text-success-base font-bold text-sm bg-success-base/10 px-3 py-1 rounded-full">Highly Stable</span>
               </div>
               <p className="text-sm text-text-secondary leading-relaxed mt-1">You sustain target earnings on 92% of active working days, enabling a 5% baseline premium reduction.</p>
             </div>
           </div>

           <div className="bg-gradient-to-r from-accent-base/10 to-transparent p-5 rounded-xl border-l-4 border-accent-base mt-4 shadow-sm">
             <div className="flex items-start gap-4">
               <ShieldAlert className="text-accent-hover shrink-0 mt-1" size={20} />
               <p className="text-sm text-white/90 font-medium leading-relaxed">Your high AI Confidence Score guarantees you Top-Tier Automated Relief. Parametric triggers will disburse claims locally in &lt;2 mins seamlessly.</p>
             </div>
           </div>
        </div>

      </div>
    </div>
  );
}
